### ISSUE TITLE
Question: How does this mechanism with concurrent requests? Does it work within transactions? Errors?

### ISSUE THREAD

**Issue by kevin-mitchell** [stelescuraul/rls#172]
I have a few questions about the mechanism this library uses to actually set / unset the values used for the RLS policy checks. I am neither a Postgres or a RLS expert, so forgive me if these questions are overly simplistic or out of place!

1. Can you tell me anything about the mechanism the library uses to prevent the tenant id / author id "bleeding" into subsequent requests? In a situation where connection pooling is happening and a connection might be shared by different tenants, is there an opportunity for bleed over?
2. Does this library work both in and out of a transaction? If I use the `manager` to create a new transaction, and make several queries inside of it, will the tenant id / author id be set appropriately for all of those queries within the transaction?
3. I see that you both `set` and `unset` the tenant / author ids. Say I write a very bad, invalid query, is there a chance that the query will fail in such a way that the tenant / author id would not be appropriate "unset" and so would have a potential of bleeding into subsequent requests with different tenants re-using the connection?

Again, these questions may all be super short sighted / simplistic or just irrelevant (because of the mechanism being used), sorry in advance if that's the case but thanks for any assurances :)

**Comment by stelescuraul** [comment]
Thanks for the interest in the library @kevin-mitchell. 
First of all I'd like to start by saying that there's no guarantees or assurances about the library. This library is provided as is without any responsibility. Please check the license.

1. There is not much I have done for this library to make things work. There's a few subtle cases where things needed a bit more tweaking (transactions) but overall all this library does, it taps into the lowest level in typeorm where the actual query is made -> `PostgresQueryRunner` and adds two queries: one before the user query (`SET`) and one after the user query (`RESET`). In Typeorm, once you have a query runner, you have a connection from the database pool (pg pool i believe). There are multiple ways you can get this query runner, you can either create it yourself, get it from a transaction when you start it or let typeorm automatically create them for each query you make. 
So the cases here are:
i. You create and manage your own query runner -> that's basically getting and using one connection from the pool until you `releaseQueryRunner()`. In here each query gets wrapped with `SET` and `RESET`.
ii. You let typeorm manage the creation of the query runner -> when you make any query (eg: `entity.find()`) typeorm creates a queryrunner (by getting the connection from the pool) and when the [query](https://github.com/Avallone-io/rls/blob/master/lib/common/RLSPostgresQueryRunner.ts#L30) function is executed, it will have the following flow using the same connection : `set rls` -> `find()` -> `reset rls` 
iii. If you use transactions, it is a combination of the two points above (it's an oversimplification) where typeorm creates a query runner for you and then gives you access to it. So the flow of queries is: `SET TRANSACTION` -> `set rls` -> `query` ->`reset rls` ->  `COMMIT/REVERT`
2. It works with transactions. You can have a look at the tests regarding this in here: https://github.com/Avallone-io/rls/blob/master/test/common/EntityManager.spec.ts#L284
3. In theory even if you have a bad query that would leave the tenant configuration on a connection, the next query would do a `set` so it would overwrite the previous value from the bad query. Seeing this question made me think that there _might_ be a very edge case where the `reset` might not happen. I will write the tests for it to confirm in the weekend and I`ll push a fix if that's the case (needs validation first).

Feel free to test the library as you sit fit and if you find bugs, please submit a test case to be able to reproduce it.

In the future I will be looking into `set local` from postgres. It currently breaks some tests so I have not looked into it in depth.

**Comment by k-atama** [comment]
Just wanted to say thank you very very much for taking the time to provide such a great response. I really appreciate it.

I've since read through the code / tests and understand what you're referring to. I feel like this ticket could be closed now.

Our fairly large code base essentially "just worked" after switching from DB user based RLS to a `set rls.tenant_id ...` style RLS policy. There was one place there we were (possibly "badly") using `[an array].map(...` to write a bunch of data within a transaction, and this appears to have thrown things off with either the library or Postgres itself. I will try to reproduce and if / when I do will open a ticket if it seems like a defect with the library (although again, I suspect it may simply be an issue with how we were querying within a transaction!).

Thanks again!

**Comment by stelescuraul** [comment]
Thanks for the follow up! I'm really happy to hear others are using the library and that it actually solves the problem!

Regarding point 3 from the previous comment, I mentioned I might have found an edge case for not reseting the environment. Indeed that was the case and there's a [PR ](https://github.com/Avallone-io/rls/pull/176) fixing it. You can read the details in the PR description. You can expect this to be merged on Monday. 

Also, please let me know if you managed to find any issues with the transition. I will keep the issue open until the release of the fix and then close it.

**Comment by stelescuraul** [comment]
I have released the fixes. It was a bit messy since I have never maintained multiple versions but I finally got it working and the fix is now released for 2.x and backported to 1.x as well.
I`ll close this issue for now. Please let me know if you encounter any other issues!
