### ISSUE TITLE
Is there a way to set the tenant After the request has gone through the controller?

### ISSUE THREAD

**Issue by czioutas** [stelescuraul/rls#203]
Hello,

We are using nestjs and just added the rls package. 
Everything works fine but we have a case in which the tenant_id is only know after we hit the request and do some processing.
Is it possible to set it afterwards?

We tried setting it on the connection from the RLS Connection injection but that did not affect the repository.

Thank you!

**Comment by stelescuraul** [comment]
Hi @czioutas ,

If you only need this in some very few cases, the easiest way is to create a separate `RLSConnection` once you know the `tenant_id` and `actor_id`. You can do something like this in your service:

```ts
   // find the tenantId and actorId somehow
   // You can even use the `this.typeormConnection` to call DB outside of RLS scope. 
   // Make sure your policies allow you to do that if you need it
   // this.typeormConnection is the raw typeorm Connection / Datasource.

    const rlsConnection = new RLSConnection(this.typeormConnection, {
      tenantId: tenantId,
      actorId: actorId,
    });

    // Get the user repo from the custom connection
    const  tenantUserRepo = rlsConnection.getRepository(User);

   const user = await tenantUserRepo.findOne(...);
   // Here you just do your queries
```

The above solution will not propagate to other services so you will need custom functions to pass the needed connection. Alternatively, you can use a transaction and pass the entity manager, it is much easier to coordinate. 

```ts
   // building on top of the above example

   return await transaction(rlsConnection, async entityManager => {
        const transactionalUserRepo = entityManager.getRepository(User);
        // do something with transactionalUserRepo

        await service.doSomething(entityManager); -> pass the manager to stay within the same transaction
   });
```

The `transaction` function above is a custom wrapper (helper function) to abstract creating a transaction from a connection. 

Do you need to use this in a regular api server, or is this part of a lambda?
Let me know if this answers your question.

**Comment by czioutas** [comment]
Hey @stelescuraul thanks for the reply!

Ye I see your solution, although it wouldnt work for us as there are cases where the same service is either initiated by a tenant aware request of from another service that calculates it. 

I was looking to see how we can change the value of tenantId within the connection - but I think the issue is that I am not fully aware of how the connection is being used by the repos (reference etc).
I had an idea but bear with me if its completely wrong.

In RLSConnection there is tenancyModelOptions - if we would allow this to be modified would that help? I am not sure when the  createQueryRunner is being called. My background is mainly .net so the whole connection scope is very different.

Thank you nevertheless for your work - wonderful package and we still managed to do some tricks to use it even with this limitation due to our approach.

**Comment by stelescuraul** [comment]
@czioutas Would you be able to provide a small example? I am not sure I understand the use case that the above approach can't solve :thinking: 

Regarding the `tenancyModelOptions`, I think that allowing whoever uses the connection to mutate the properties could be a security risk (maybe?) but also introduces extra complexity.

**Comment by stelescuraul** [comment]
I am closing this for now since it's become stale. @czioutas if you need more assistance, please leave a comment.
