### ISSUE TITLE
Any SQL errors in a transaction are masked

### ISSUE THREAD

**Issue by karvapallo** [stelescuraul/rls#213]
Any errors that happen during a transaction, are masked by the `current transaction is aborted, commands ignored until end of transaction block` error, due to the call made to `await super.query('reset rls.actor_id; reset rls.tenant_id;');`despite there being an error and the call being transactional.

I believe the solution to this issue would be to check if `this.isTransactionActive` is true and if there is an error, do not attempt to run the `reset rls.actor_id; reset rls.tenant_id;` query.

**Comment by stelescuraul** [comment]
Thank you @karvapallo for your contribution. This is now released as version `2.0.4`.
I would like to back-port this to version 1 of rls. Do you want to add the same changes but into branch `1.x` ? Otherwise I can do it as well, but it would be nice to have your name as contributor on the PR.

**Comment by karvapallo** [comment]
@stelescuraul thanks! You can go ahead and make that changes to version `1.x`. Thanks again.
