### ISSUE TITLE
Is there a way do define RLS with a decorator?

### ISSUE THREAD

**Issue by omerd-cyera** [stelescuraul/rls#33]
Im trying to enable RLS from code, and cant seem to find how to do it.
if you know of a way ill be happy to know about it, and if not, we can create a decorator in this repo.

**Comment by stelescuraul** [comment]
Can you please elaborate what is the expected function you'd like ? I am not sure what you mean by "enable RLS from code".
Maybe you can give a few examples ? @od-cyera

**Comment by omerd-cyera** [comment]
I mean like a migration or some other config to enable row level security on the tables and define the policies during synchronize. currently i just wrote a migration to to that, but seems nice to me if it would be integrated

**Comment by stelescuraul** [comment]
This package is only responsible for setting up the correct runtime parameters. Creating the policies is outside of the scope for this.
I believe that if we add support for policies we would potentially need to support many permutations of them. Another consideration is that the policies are (and should be) custom per each use case.

This feature would sound more like a `typeorm` feature instead: whenever a new table is created, apply `this` sql query for it (this is where you'd add your policy). 

The way I handle the policies is by creating utility functions to abstract away some of the boilerplate code needed for each table and using that after each table creation in the migration directly.

**Comment by omerd-cyera** [comment]
I'm not sure i fully understand your solution, could you share a snippet?
maybe there is a way to add that abstract function to the repo so other people wont have to write the migration from scratch..
I don't know typeorm in depth.. maybe there is a feature that can help here..

**Comment by stelescuraul** [comment]
What i'm trying to say here is that this package is not responsible for the policies that need to be applied at the database level.
The RLS policies are independent and custom for each consumer of this library and wouldn't want to add constraints on how to write those policies.
The policy from the Readme is an **example** and it is there to emphasise the fact that this library will set the values `rls.tenant_id` and  `rls.actor_id`. The creation of the policy is up to every user. 

With that out of the way, here's an example of some helper functions I created to make things easier when creating tables: 
```ts
export function createTenantRLSPolicy(
  schema: string,
  tableName: string,
  property: string,
) {
  return `
        CREATE POLICY rls_tenant_isolation ON "${schema}"."${tableName}" for ALL
        USING ("${property}" = current_setting('rls.tenant_id')::uuid);
    `;
}

export function enableRLS(schema: string, tableName: string) {
  return `
        ALTER TABLE "${schema}"."${tableName}" ENABLE ROW LEVEL SECURITY;
    `;
}
```

You'd end up using this within the migration that creates a table. For example: 
```ts
    await queryRunner.query(`
        ${createTenantRLSPolicy('schema', 'table', 'tenant_column_name')}
        ${enableRLS('schema', 'table')}
    `);
```

For examples on how to write those policies, I'd suggest that you refer to: 
* https://www.postgresql.org/docs/current/ddl-rowsecurity.html 
* https://www.postgresql.org/docs/current/sql-createpolicy.html
* https://www.enterprisedb.com/postgres-tutorials/how-implement-column-and-row-level-security-postgresql
* https://aws.amazon.com/blogs/database/multi-tenant-data-isolation-with-postgresql-row-level-security/

I will update the readme to be more clear in a future release and add some examples there.

**Comment by omerd-cyera** [comment]
Thanks! 
how do you define/run the migration so it runs on every table?
I wrote a migration that goes over all the tables and enables RLS,
but lets say I add another table and generate a migration. the next time i run the migrations, the new table wont have RLS enabled...
did you manage to solve this problem some how?

here is a snippet of the migration
```typescript
class tenantIsolation implements MigrationInterface {
  async getTableNames(queryRunner: QueryRunner): Promise<Table[]> {
      const viewNames = (await queryRunner.getViews()).map((view) => view.name);
      return (await queryRunner.getTables()).filter(
        (table) =>
          !table.name.includes('pg_catalog.') &&
          !table.name.includes('information_schema.') &&
          table.name !== 'migrations' &&
          table.name !== 'typeorm_metadata' &&
          !viewNames.includes(table.name),
      );
    }
  
    public async up(queryRunner: QueryRunner): Promise<void> {
      const tables = await this.getTableNames(queryRunner);
  
      await Promise.all(
        tables.map(async (table): Promise<void> => {
          await queryRunner.query(
            `CREATE POLICY ${policyName} ON "${table.name}" for ALL USING (...)`,
          );
          await queryRunner.query(
            `ALTER TABLE "${table.name}" ENABLE ROW LEVEL SECURITY`,
          );
        }),
      );
    }
}
```

**Comment by stelescuraul** [comment]
> how do you define/run the migration so it runs on every table?

This is what I meant when I said that it sounds like a `typeorm` feature. Currently I am not aware of a way to run some arbitrary query on each table creation. You'd have to ensure that manually somehow. 

The way I am managing that particular scenario for now, is through manual review unfortunately. However, I will be looking into DDL event triggers for postgres.
Idea: You could create an event trigger that can identify when a table is created, and apply RLS for it. I have not tested this and it is on my roadmap to validate. For reference you can check:
* https://blog.dbi-services.com/can-i-do-it-with-postgresql-16-ddl-triggers/
* https://www.postgresql.org/docs/current/event-trigger-definition.html
* https://www.postgresql.org/docs/current/sql-createeventtrigger.html

If you would like to explore this option, feel free to post back here your findings :slightly_smiling_face: .
I'll keep this issue open for now, but I think the further dicussions are out of the scope for the library. In case the above idea works, I can add it to the documentation.

**Comment by omerd-cyera** [comment]
Thanks! looks like a promising solution.. 
Ill post back when I have something that works.

**Comment by stelescuraul** [comment]
I closed this issue. We can mark this as resolved for now.
Please feel free to write down your findings if you'd like :)
