### ISSUE TITLE
What is the purpose of actor_id?

### ISSUE THREAD

**Issue by raman-nbg** [stelescuraul/rls#53]
Nice library! This is exactly what I'm looking for.

But I can think what the actor_id is used for. Should this be used somewhere in the policies, too? As I know you were inspired by the AWS Blog Post (https://aws.amazon.com/de/blogs/database/multi-tenant-data-isolation-with-postgresql-row-level-security/). I can't find anything about actors in this blog post.

- What is the purpose of actor id? Is this something like the user id?
- Is it ok to set the actor id to an empty string or even to null?

**Comment by stelescuraul** [comment]
Hi @raman-nbg, thanks for the feedback :) 

The `actor_id` is another point that you can use to create your policies. For example, using `tenant_id` allows you to split (isolate) the data by tenant (organization). Say that you further want to isolate the data for each user. This is where the `actor_id` comes into play and it allows you to create policies that further more isolate the data. Either only by tenant, actor (user) or both: a user within a tenant. 

Your intuition was right, the actor_id is basically some kind of user id. It is up to you how / what you will use it for. Another use case for this is to know who is the person that generated the database query. For example, person John (`actor_id=1`) created company A in tenant `Foo`. You can use the `actor_id` either to apply policies, generate logs or simply ignore it if you don't need it. 

It is okay to set it to `null` if you don't have policies using it.
